---
title: "Research"
---

## Published Articles and Book Chapters

- Ana Ubilava. '[Amicable Settlements in Investor-State Disputes: Empirical Analysis of Patterns and Perceived Problems]( https://brill.com/view/journals/jwit/21/4/article-p528_2.xml){target="_blank"}' (2020) 21(4) The Journal of World Investment & Trade 528-557.
- Ana Ubilava and Luke Nottage, 'Novel and Noteworthy Aspects of Australia’s Recent Investment Agreements and ISDS Policy: The CPTPP, Hong Kong, Indonesia and Mauritius Transparency Treaties” in in Nottage, Luke; Ali, Shahla; Jetin, Bruno; Teramura, Nobumichi (eds), '[New Frontiers in Asia-Pacific International Arbitration and Dispute Resolution](https://lrus.wolterskluwer.com/store/product/new-frontiers-in-asia-pacific-international-arbitration-and-dispute-resolution/){target="_blank"}" (Wolters Kluwer 2021).
- Luke Nottage and Ana Ubilava, “Costs, Outcomes and Transparency in ISDS Arbitrations: Evidence for an Investment Treaty Parliamentary Inquiry” (2018) 21(4) International Arbitration Law Review 111-7.
- Luke Nottage and Ana Ubilava, “Asia's Changing International Investment Regime: Sustainability, Regionalization and Arbitration”, (2018) 44(2) UWA L Rev 195-208 and [Sydney Law School Research Paper No. 18/34](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3191718){target="_blank"}.


## Blog Posts

- Ana Ubilava, '[Mandatory Investor-State Conciliation in New International Investment Treaties: Innovation and Interpretation](http://mediationblog.kluwerarbitration.com/2020/09/05/mandatory-investor-state-conciliation-in-new-international-investment-treaties-innovation-and-interpretation/){target="_blank"}', Kluwer Mediation Blog (Blog Post, 5 September 2020).
- James Claxton, Luke Nottage and Ana Ubilava, '[Pioneering Mandatory Investor-State Conciliation Before Arbitration in Asia-Pacific Treaties: IA-CEPA and HK-UAE BIT](http://arbitrationblog.kluwerarbitration.com/2020/09/05/pioneering-mandatory-investor-state-conciliation-before-arbitration-in-asia-pacific-treaties-ia-cepa-and-hk-uae-bit/){target="_blank"}', Kluwer Arbitration Blog (Blog Post, 5 September 2020). 
- Ana Ubilava and Luke Nottage, '[ICSID’s New Mediation Rules: A Small but Positive Step Forward](https://icsid.worldbank.org/sites/default/files/amendments/public-input/Ubilava_Notage_10.17.2018.pdf){target="_blank"}', (2018) ICSID Website (Submission to ICSID on ICSID Rules and Regulations Amendment Process). 
- Ana Ubilava, ‘[International Investment Arbitration Across Asia: A Symposium](http://arbitrationblog.kluwerarbitration.com/2017/03/01/international-investment-arbitration-across-asia-symposium/){target="_blank"}’, Kluwer Arbitration Blog (Blog Post, 1 March 2017).

